name: Build and Deploy
permissions: write-all
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '18.x'
    - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-    
    - name: Build
      run: |
        npm install @angular/localize --save --legacy-peer-deps
        npm install --legacy-peer-deps
        npm run-script deploy
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/tapitas-top
    - uses: actions/checkout@v3
      with:
          ref: gh-pages
    - name: Copy index.html to 404.html
      run: |
        cp index.html 404.html
        git config user.name jaimejj54
        git config user.email ${{ secrets.EMAIL }}
        git add .
        git commit -m "404.html copied"
        git push
